## This is part of the RTD template
#[build-system]
#requires = ["flit_core >=3.2,<4"]
#build-backend = "flit_core.buildapi"

[project]
name = "Wesician"
authors = [{name = "Wesician", email = "damien@alphagame.dev"}]
dynamic = ["version", "description"]
